### ISSUE TITLE
The password of baidu cloud disk of the pre-trained model

### ISSUE THREAD

**Issue by wuxifang1994** [XavierCHEN34/Human-Parsing#1]
Hi,thank you for your great work. Would you mind send me your password of the baidu cloud disk of the pre-trained model? Thanks again.

**Comment by wuxifang1994** [comment]
> Hi,thank you for your great work. Would you mind send me your password of the baidu cloud disk of the pre-trained model? Thanks again.

**Comment by ru4691** [comment]
Hi, thank you for your great work. Would you mind send me your password of the baidu cloud disk of the pre-trained model? Thanks again.
